# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: azure-aci
- name: buildConfiguration
  value: Release
- name: SERVICE_PRINCIPAL_ID
  value: 77e191d7-8b96-45ac-bf33-7311f7cc9049
- name: SERVICE_PRINCIPAL_NAME
  value: https://VisualStudio/SPN94662d0a-cfb1-4cb0-bd79-bdece183481a
- name: ACR_N
  value: pipelinenoetapp
- name: ACR_REG_ID
  value: /subscriptions/160a804a-ab3b-4d4d-ac48-0d575a8dc8f0/resourceGroups/pipeline/providers/Microsoft.ContainerRegistry/registries/pipelinenoetapp



steps:
- script: echo $(USERNAME)
- script: echo $(dummy)

# its working, no need to create a lot of RG
# - task: AzureCLI@2
#   inputs:
#     azureSubscription: 'Visual Studio Professional(160a804a-ab3b-4d4d-ac48-0d575a8dc8f0)'
#     scriptType: 'bash'
#     scriptLocation: 'inlineScript'
#     inlineScript: 'az group create -l westus -n MyResourceGroupBatch'

- task: CmdLine@2
  inputs:
    script: 'echo $(dummy)'


- task: AzureCLI@2
  displayName: Show ACR 
  inputs:
    azureSubscription: 'Visual Studio Professional(160a804a-ab3b-4d4d-ac48-0d575a8dc8f0)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az acr repository show -n pipelinenoetapp --repository pipelinenoetapp.azurecr.io/pipelinenoetapp'

- task: AzureCLI@2
  displayName: Role assingment
  inputs:
    azureSubscription: 'Visual Studio Professional(160a804a-ab3b-4d4d-ac48-0d575a8dc8f0)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az role assignment list'

- task: AzureCLI@2
  displayName: Test ACR_REGISTRY_ID
  inputs:
    azureSubscription: 'Visual Studio Professional(160a804a-ab3b-4d4d-ac48-0d575a8dc8f0)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az acr show --name $(ACR_N) --query id --output tsv

- task: Docker@2
  inputs:
    containerRegistry: 'acrServiceConnection'
    command: 'login'

- task: CmdLine@2
  inputs:
    script: 'az ad sp list --show-mine'

- task: AzureCLI@2
  displayName: Create Cluster AKS
  inputs:
    azureSubscription: 'Visual Studio Professional(160a804a-ab3b-4d4d-ac48-0d575a8dc8f0)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az aks create --resource-group pipeline --name myAKSCluster --node-count 2 --generate-ssh-keys  --attach-acr pipelinenoetapp

# - task: AzureCLI@2
#   inputs:
#     azureSubscription: 'Visual Studio Professional(160a804a-ab3b-4d4d-ac48-0d575a8dc8f0)'
#     scriptType: 'bash'
#     scriptLocation: 'inlineScript'
#     inlineScript: |
#        SERVICE_PRINCIPAL_NAME=https://VisualStudio/SPN94662d0a-cfb1-4cb0-bd79-bdece183481a
#        # ACR_REGISTRY_ID=$(az acr show --name $(ACR_N) --query id --output tsv)
#        echo $(ACR_REG_ID)
#        az role assignment create --assignee $(SERVICE_PRINCIPAL_ID) --scope $(ACR_REG_ID) --role acrpull
