# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  group: aci

steps:
- script: echo $(USERNAME)
- script: '$(USERNAME)'
- script: $(USERNAME)

- task: CmdLine@2
  inputs:
    script: 'az login'

- task: CmdLine@2
  inputs:
    script: 'az group create -l westus -n MyResourceGroup'

- task: CmdLine@2
  inputs:
    script: 'az group create -l westus -n MyResourceGroup'
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Visual Studio Professional(160a804a-ab3b-4d4d-ac48-0d575a8dc8f0)'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: 'az group create -l westus -n MyResourceGroup'

